Organise structure of problems docs
fitbenchmarking/fitbenchmarking pull request #1015
Opened 2022-01-07 17:20 UTC by AndrewLister-STFC

#### Description of Work
Ensure that all problem sets have a descriptions with the following:
 - Download links
 - Information on source of data
 - Information on size of problem -- unknowns and data points.

Currently there is a folder on powell with new versions of everything in generated by:
```
for d in $(ls examples/benchmark_problems); do zip -r ${d}.zip $d; done
for d in $(ls examples/benchmark_problems); do tar -czvf ${d}.tar.gz $d; done
```

Fixes #1003 

#### Testing Instructions

1. Look at the files on powell (called `fitbenchmarking-new` in samelocation as live files)
2. Proof read docs
3. Check links appear to work

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

2022-01-24 14:36 UTC, tyronerees requested changes
I think there's a couple of mantid warnings missing -- otherwise all looks good to me!

2022-01-24 14:36 UTC, tyronerees commented on docs/source/users/BenchmarkProblems.rst
> +
```suggestion
.. warning::   
   |MantidWarning|
```

2022-01-24 14:36 UTC, tyronerees commented on docs/source/users/BenchmarkProblems.rst
> +
```suggestion

.. warning::   
   |MantidWarning|
```

2022-01-26 10:08 UTC, tyronerees commented on docs/source/users/BenchmarkProblems.rst
> +
Sorry, I think I got the whitespace wrong here -- it comes out like: 
![image](https://user-images.githubusercontent.com/13645545/151143965-31d2552a-6559-43fc-9272-881b6b9e19da.png)

2022-01-26 10:10 UTC, tyronerees commented
I've just noticed that the spacing at the start of the file is a bit wonky too:
![image](https://user-images.githubusercontent.com/13645545/151144157-86e29219-4d33-4bdd-b161-c9672467a4d7.png)

I can't see how this can be new, but I think it was correct on my first pass through(?)

2022-01-26 13:18 UTC, AndrewLister-STFC commented on docs/source/users/BenchmarkProblems.rst
> +.. warning::
```suggestion

.. warning::
```

2022-01-26 13:18 UTC, AndrewLister-STFC commented on docs/source/users/BenchmarkProblems.rst
> +.. warning::
```suggestion
.. warning::
```

2022-01-26 13:51 UTC, tyronerees approved these changes

2022-01-26 13:52 UTC, tyronerees commented
All looks good -- @AndrewLister-STFC, can you amend the directory on Powell?

2022-01-26 13:52 UTC, merged