882 lm herbert
fitbenchmarking/fitbenchmarking pull request #1033
Opened 2022-03-01 15:56 UTC by tyronerees

#### Description of Work

Fixes #882 

#### Testing Instructions

1. Run on a matlab-enabled machine
2. Check that Horace/lm-lsqr works as expected
3. Check that the tests are correct **The regression test needs updating**
4. Check that the docs make sense and are complete.

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

2022-03-01 16:49 UTC, AndrewLister-STFC reviewed
Spotted some typos but looks good in general. I'll run the tests and update the regressions before merging

2022-03-01 16:49 UTC, AndrewLister-STFC commented on examples/all_softwares.ini
> +	  horace
Mind if we change this tab to the equivalent in spaces?
```suggestion
          horace

```

2022-03-01 16:49 UTC, AndrewLister-STFC commented on fitbenchmarking/controllers/horace_controller.py
> +    Controlller for fit in Herbert
```suggestion
    Controller for fit in Herbert
```

2022-03-01 17:01 UTC, tyronerees commented
@AndrewLister-STFC -- do you know how to make this link point to this heading: 

![image](https://user-images.githubusercontent.com/13645545/156213899-f1c236e2-bb18-4964-9bfd-d268167bd5db.png)

Using the title of the heading as the target takes it to the minimizer page of MATLAB.  Setting up a target like this doesn't seem to work either:
![image](https://user-images.githubusercontent.com/13645545/156214081-14e9a521-506a-4ab5-8eda-d55a462047bb.png)

Any suggestions?

2022-03-01 17:12 UTC, AndrewLister-STFC commented on docs/source/users/install_instructions/externals.rst
> +.. _matlab-install:
```suggestion
.. _matlab-install:

```

2022-03-01 17:18 UTC, AndrewLister-STFC commented
@tyronerees Fixed! It just needs a newline between anchor and heading

2022-03-15 16:30 UTC, AndrewLister-STFC requested changes
Just 1 minor fix that I'll commit then merge

2022-03-15 16:30 UTC, AndrewLister-STFC commented on examples/all_softwares.ini
> +          levmar
```suggestion
          horace
          levmar

```

2022-03-15 16:31 UTC, AndrewLister-STFC commented on examples/all_softwares.ini
> +          mantid
```suggestion
          levmar
          mantid
```

2022-03-15 16:31 UTC, AndrewLister-STFC approved these changes

2022-03-15 16:38 UTC, merged