Add ceres software
fitbenchmarking/fitbenchmarking pull request #1072
Opened 2022-10-19 12:25 UTC by joshuadkitenge

#### Description of Work

Add ceres solver into fitbenchmarking 

#### Testing Instructions

1.
2.
3.

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

2022-10-21 09:07 UTC, joshuadkitenge commented
https://notes.andrewtorgesen.com/doku.php?id=public:ceres

2022-10-26 10:17 UTC, joshuadkitenge commented
@AndrewLister-STFC 
**[ACTION]** Build docker container for ceres to fix failing test

2022-11-09 15:27 UTC, tyronerees requested changes
I've run locally on a couple of different cost functions and data sets, and all seems to work for me.

There's one minor documentation wording suggestion I've made, and one of the unit tests seems to be failing. 

Thanks for this -- it's great to have CERES here in FitBenchmarking 😄

2022-11-09 15:27 UTC, tyronerees commented on docs/source/users/options/minimizer_option.rst
> +**Licence** Ceres Solver is available `here <http://ceres-solver.org/license.html>`__
```suggestion
**Licence** Ceres Solver is available under the new BSD licence -- details can be found `here <http://ceres-solver.org/license.html>`__ 
```

2022-11-10 14:25 UTC, merged