Headings in options #678
fitbenchmarking/fitbenchmarking pull request #1076
Opened 2022-10-31 11:38 UTC by Shanrahan16

#### Description of Work

Fixes #678

2022-11-02 09:59 UTC, tyronerees requested changes
I think we should also merge the `SECTIONS` in `fitbenchmarking/utils/options.py` too -- breaking the convention of one doc page per section for these two sections is likely to confuse users.

2022-11-02 09:59 UTC, tyronerees commented on docs/source/users/options/output_option.rst
> +The plotting section contains options to control how results are outputted and presented.
I think we should merge `Plotting` into `Output`, not `Output` into `Plotting`; plotting is a form of output, but I'd never to think to look for where to set the output directory under a section called `Plotting`.

2022-11-02 09:59 UTC, tyronerees commented on docs/source/users/options/output_option.rst
>      [OUTPUT]
All the headers should be the same now -- either all `[OUTPUT]` or all `[PLOTTING]`

2022-11-07 16:53 UTC, Shanrahan16 commented
I think I also need to update the ini file templates

2022-11-09 15:53 UTC, tyronerees approved these changes
Works for me, and looks much cleaner -- thanks!

2022-11-09 15:53 UTC, tyronerees commented on docs/source/extending/options_extend.rst
>  To add a new option to one of the five sections ``FITTING``, ``MINIMIZERS``,
I love how the number of sections is now correct, since you've taken one out 😆

2022-11-09 15:53 UTC, merged