Remove hessian required minimizers for scipy default #1114
fitbenchmarking/fitbenchmarking pull request #1119
Opened 2023-01-13 10:27 UTC by joshuadkitenge

#### Description of Work

Fixes #1114

#### Testing Instructions

1.
2.
3.

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

2023-01-20 09:44 UTC, jess-farmer reviewed
Just have one comment - I think it would be good to add a note to the minimizer options page in the docs to let users know that hessian required minimizers have to be set explicitly in order to be run

2023-02-14 10:53 UTC, joshuadkitenge commented
Some of the documentation had incorrect formatting. I've fixed that in the latest commit.

2023-02-14 16:42 UTC, jess-farmer requested changes
Just two very minor changes, otherwise looks good!

2023-02-14 16:42 UTC, jess-farmer commented on docs/source/users/options/minimizer_option.rst
> +.. code-block:: rst
```suggestion
.. code-block:: rst

```
There should be a blank line here for the code-block to work

2023-02-14 16:42 UTC, jess-farmer commented on docs/source/users/options/minimizer_option.rst
> +   set it as above.
```suggestion
   The Hessian enabled solvers are not run by default when `scipy` software is selected. In order to run these minimizers, you must explicitly
   set them as above.
```

2023-02-16 10:03 UTC, jess-farmer approved these changes

2023-02-16 10:03 UTC, merged