Table text colors
fitbenchmarking/fitbenchmarking pull request #1141
Opened 2023-03-15 04:35 UTC by RabiyaF

**Description of Work**

The text colour in the output tables is now selected based on the contrast ratio. The contrast ratio is calculated according to the Web Content Accessibility Guidelines (WCAGs).

[Contrast ratio](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html#dfn-contrast-ratio)
[Relative Luminosity](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html#dfn-relative-luminance)

The contrast ratio is calculated between the background colours from the matplotlib colourmap and the foreground text option of either white or black. White is the default text colour. It is selected if it meets the AAA WCAGs for contrast ratio. If the requirement is not met, the text colour with the greatest contrast ratio is selected between white and black.  

**Function: Does the change do what it's supposed to?**
The tables are now displayed with more accessible text. The text should be accessible even when non default colormaps are used.

**Tests: Does it pass? Is there adequate coverage for new code?**
The expected results (acc.html, compare.html, runtime.html and local_min.html) for test_tables.py are updated.

2023-03-20 16:10 UTC, AndrewLister-STFC requested changes
This looks really good. I tested it locally and it looks to do the right thing, did you get any feedback from Jacob on this?

I only had some minor points.

2023-03-21 21:56 UTC, RabiyaF commented on fitbenchmarking/results_processing/base_table.py
> +            else:
I defined the `get_hyperlink()` method in the base class and then overwrote it in `compare_table.py`. It uses the following snippet:

`def get_hyperlink(self, result, val_str, text_col):`
`         val_str = val_str.split('<br>')`
`         val_str = [super().get_hyperlink(result, val, col)
                   for val, col in zip(val_str, text_col)]`
`         val_str = ''.join(val_str)`
`         return val_str`

It works. However, the tests fail. For now I will use a `get_hyperlink()` definition in `compare_table.py` that does not call the super method.

2023-03-30 12:42 UTC, AndrewLister-STFC requested changes
This looks great! Looks like there're a few conflicts because the tests for outputs have been changed slightly. Would you mind regenerating the tables then I think we can merge this. 🚀

2023-03-30 22:53 UTC, RabiyaF commented
I think that I have managed to resolve the merge conflicts. But I am not sure why the checkpointing test is failing on Windows.

2023-03-31 08:57 UTC, AndrewLister-STFC approved these changes
Looks great! I've opened a PR to fix the windows tests issue (which is nothing to do with this PR).

2023-03-31 08:58 UTC, merged