Measure energy usage instead of emissions
fitbenchmarking/fitbenchmarking pull request #1377
Opened 2024-11-12 15:59 UTC by jess-farmer

## Description of work

Fixes #1321 

## Testing Instructions

1.
2.
3.

## Checklist

- [ ] The title is of a format appropriate for a line in future release notes.
- [ ] I have added the appropriate tags to the PR.
- [ ] My PR represents one logical piece of work.
- [ ] My PR fully fixes the issue linked. If new issues have been created, what are they?
- [ ] I have added the appropriate tests to cover code that has been added.
- [ ] I have updated the documentation in the relevant places to cover the changes.

2024-11-13 14:13 UTC, RabiyaF requested changes
It looks good :) and it makes sense to shift to from carbon intensity to power usage. Just had a few suggestions.

2024-11-14 09:40 UTC, jess-farmer commented on fitbenchmarking/results_processing/fitting_report.py
> +    energy_disp = "N/A" if np.isnan(result.energy) else f"{result.energy:.4g}"
Good spot - I was intending to keep the units there just missed them off!

2024-11-14 14:43 UTC, jess-farmer commented on fitbenchmarking/core/fitting_benchmarking.py
>              self.__emissions_tracker = EmissionsTracker()
I think reducing the interval to 1 second is a good idea - I've run a few experiments today and it doesn't appear to have a major impact on runtime

2024-11-18 14:20 UTC, RabiyaF approved these changes
Everything works great 💯 Thank you for adding this to `fitbenchmarking`.

2024-11-18 14:35 UTC, merged