Cost function class
fitbenchmarking/fitbenchmarking pull request #654
Opened 2020-10-09 08:42 UTC by wathen

#### Description of Work

Fixes #489 

#### Testing Instructions

1.
2.
3.

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

2020-10-16 14:09 UTC, wathen commented on docs/source/extending/cost_function.rst
> +2. Document the available cost functions by by:
```suggestion
2. Document the available cost functions by:
```

2020-10-16 14:10 UTC, wathen commented on docs/source/extending/jacobian_extend.rst
> +When adding new cost functions, you will find it helpful to make use of the
```suggestion
When adding new Jacobian, you will find it helpful to make use of the
```

2020-10-16 14:11 UTC, wathen commented on docs/source/extending/jacobian_extend.rst
> +and subclasses of :class:`~fitbenchmarking.cost_func.base_cost_func.CostFunc` class:
```suggestion
and subclasses of :class:`~fitbenchmarking.cost_func.base_cost_func.CostFunc`:
```

2020-10-16 14:12 UTC, wathen commented on docs/source/users/options/fitting_option.rst
> +* ``nlls`` - This sets the cost function to be weighted or non-weighted non-linear least squares.
```suggestion
* ``nlls`` - This sets the cost function to be weighted or non-weighted non-linear least squares, the weighting is controlled by the ``use_errors`` option.
```

2020-10-16 14:21 UTC, wathen commented on fitbenchmarking/cost_func/nlls_cost_func.py
> +Implements the base class for the cost function class.
```suggestion
Implements the weighted and non-weighted non-linear least squares cost function```

2020-10-16 14:22 UTC, wathen commented on fitbenchmarking/jacobian/base_jacobian.py
> +    def cached_func_values(self, cached_dict, eval_modelunc, params, **kwargs):
```suggestion
    def cached_func_values(self, cached_dict, eval_model, params, **kwargs):
```

2020-10-16 14:22 UTC, wathen commented on fitbenchmarking/jacobian/base_jacobian.py
> +            value = eval_modelunc(params, **kwargs)
```suggestion
            value = eval_model(params, **kwargs)
```

2020-10-16 14:25 UTC, wathen commented on fitbenchmarking/parsing/tests/test_parsers.py
> +                actual = fitting_problem.function(x, *r[1])
```suggestion
                actual = fitting_problem.eval_f(x=x, params=r[1])
```

2020-10-28 09:54 UTC, tyronerees requested changes
I don't think the two files `.coverage` and `file` should be in the repository.

I think we need to document this a little more -- it's not clear to me what should go in `eval_r` or in `eval_cost`.  

Is `eval_r` always 
![image](https://user-images.githubusercontent.com/13645545/97415299-efdd1200-18fc-11eb-849e-3e9484e8ace3.png)
If so it should (a) be in the `FittingProblem` class, and (b) that would mean we couldn't solve, say, weighted non-linear least squares using a non-linear least squares solver (unless we put another layer on top, which is possible).

Otherwise, we could say that it solves
![image](https://user-images.githubusercontent.com/13645545/97415446-29158200-18fd-11eb-9d33-a1f216d05178.png)
where eval_cost is c(.) and eval_r is r(.).  This would let us solve problems like 
![image](https://user-images.githubusercontent.com/13645545/97415804-8dd0dc80-18fd-11eb-8b91-b115f0aed850.png)
and 
![image](https://user-images.githubusercontent.com/13645545/97415917-b062f580-18fd-11eb-9a05-2a37e7c5273d.png)
using Levenberg-Marquardt type methods (say).  However, there are some methods that can cope with weighting, say, internally (Mantid and RALFit, or the top of my head), and this would add additional overhead.  We should discuss.

I checked this branch against master with the NIST test set and all Mantid (function evaluation only), Sci_ls (eval_r) and minuit (eval_cost), and the accuracy results were identical.

2020-10-29 08:59 UTC, tyronerees approved these changes

2020-10-29 09:02 UTC, tyronerees commented
Will update the docs in #490

2020-10-29 09:02 UTC, merged