Options printing
fitbenchmarking/fitbenchmarking pull request #664
Opened 2020-10-13 13:03 UTC by wathen

#### Description of Work

Fixes #663 
Fixes #658 

Adds options printing to `DEBUG` log level and prints warning if `options.result_dir` is set to be the default.

#### Testing Instructions

1. Check options printing works for `DEBUG` log level
2. Check the wording of the warning for the results directory

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

2020-10-29 16:43 UTC, jfowkes requested changes
Looks good apart from two issues:

1. For software not specified in FITTING, all solvers are printed, e.g:
```
scipy = CG
scipy_ls = lm-scipy-no-jac
	lm-scipy
	trf
	dogbox
```
even though I have only specified scipy as software and GS as minimiser.

2. Folder warning message should capitalise the and to, currently it reads:
```
WARNING: 
the FitBenchmarking results will be placed into the folder: 
   /Users/jari/Code/fitbenchmarking/fitbenchmarking_results
to change this alter the input options file.```

2020-10-30 07:05 UTC, Anders-Markvardsen commented on .gitignore
> +fitbenchmarking_results/
with the renaming of result/ -> fitbenchmarking_results/, do we still want to ignore result/ also?

2020-10-30 07:12 UTC, Anders-Markvardsen commented on fitbenchmarking/cli/main.py
> +            options.DEFAULT_PLOTTING['results_dir']:
Somewhat unrelated to this PR, but what is the reason that 'results_dir' is located within

```
    DEFAULT_PLOTTING = \
        {'make_plots': True,
         'colour_scale': [(1.1, "#fef0d9"),
                          (1.33, "#fdcc8a"),
                          (1.75, "#fc8d59"),
                          (3, "#e34a33"),
                          (np.inf, "#b30000")],
         'comparison_mode': 'both',
         'table_type': ['acc', 'runtime', 'compare', 'local_min'],
         'results_dir': 'results'}
```

Does PLOTTING in DEFAULT_PLOTTING refer to anything that fitbenchmarking returns to the user? Maybe discuss this later in todays' friday catch-up

2020-10-30 15:03 UTC, jfowkes approved these changes
Looks great and works as intended for me.

2020-10-30 15:03 UTC, merged