655 datafiles
fitbenchmarking/fitbenchmarking pull request #670
Opened 2020-10-26 13:58 UTC by tyronerees

#### Description of Work

Fixes #655 

#### Testing Instructions

1.  Check that running `fitbenchmarking` works.
2.  Check the updates to the docs make sense.
3.

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

2020-10-26 15:10 UTC, wathen requested changes
Looks good, just a few doc things. Also, I think we need to update the [running docs](https://fitbenchmarking.readthedocs.io/en/latest/users/running.html) to reflect the new changes

2020-10-26 15:10 UTC, wathen commented on fitbenchmarking/cli/main.py
> +    print("root = {}".format(root))
please remove print statement

2020-10-26 15:10 UTC, wathen commented on fitbenchmarking/cli/main.py
>      epilog = '''Usage Examples:
The usage examples need to include `-p` in both and I think there should be a bit of text before the examples stating that this is run with the source code downloaded.

2020-10-28 09:54 UTC, wathen requested changes
Just a few comments but looks great in general. Once the PR has gone in will we update the pypi version?

2020-10-28 09:54 UTC, wathen commented on docs/source/users/running.rst
> +passing the path using the `--problem-sets` (or `-p`) option.
```suggestion
passing the path using the ``--problem-sets`` (or ``-p``) option.
```

2020-10-28 09:54 UTC, wathen commented on examples/benchmark_problems/NIST/META.txt
> +NIST
Is this file needed?

2020-10-28 10:13 UTC, tyronerees commented
I think we should wait until #664 goes in too, then update pypi to 0.1.dev2, do some final checks to see all works as expected, and then release 0.1.0

2020-10-28 12:26 UTC, wathen approved these changes

2020-10-28 12:26 UTC, merged