Nonlinear least squares classes
fitbenchmarking/fitbenchmarking pull request #677
Opened 2020-11-03 12:28 UTC by wathen

#### Description of Work

Fixes #671 

#### Testing Instructions

1.
2.
3.

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

2020-11-03 15:44 UTC, wathen commented on docs/source/users/cost_func.rst
> +Fitbenchmarking supports multiple different nonlinear least squares cost functions. These can be set via the `cost_func_type` option in :ref:`fitting_option`.
```suggestion
Fitbenchmarking supports multiple different nonlinear least squares cost functions. These can be set via the ``cost_func_type`` option in :ref:`fitting_option`.
```

2020-11-03 15:46 UTC, wathen commented on fitbenchmarking/jacobian/analytic_jacobian.py
> +        Evaluates Jacobian of cost_func.eval_cost
```suggestion
        Evaluates Jacobian of problem.eval_model
```

2020-11-24 13:13 UTC, tyronerees requested changes
This looks good.  

In addition to the one minor comment above, can we change `root_nlls_cost_func` to `hellinger_nlls_cost_func`?  This will link this cost function to the Hellinger distance cost function used in machine learning (see [here](https://stats.stackexchange.com/questions/154879/a-list-of-cost-functions-used-in-neural-networks-alongside-applications) or [here](http://www.tcs.tifr.res.in/~prahladh/teaching/2011-12/comm/lectures/l12.pdf)), which at least shows we haven't plucked it from thin air.

2020-11-26 11:49 UTC, tyronerees requested changes
Just a couple of doc changes needed, then all looks good to go.

2020-11-26 11:49 UTC, tyronerees commented on docs/source/users/options/fitting_option.rst
> +* ``root_nlls`` - This sets the cost function to be root non-linear least squares, :class:`~fitbenchmarking.cost_func.root_nlls_cost_func.RootNLLSCostFunc`.
```suggestion
* ``hellinger_nlls`` - This sets the cost function to be the Hellinger cost function, :class:`~fitbenchmarking.cost_func.root_nlls_cost_func.HellingerNLLSCostFunc`.
```

2020-11-26 11:49 UTC, tyronerees commented on docs/source/users/options/fitting_option.rst
> +    cost_func_type: root_nlls
```suggestion
    cost_func_type: weighted_nlls
```

2020-11-26 11:49 UTC, tyronerees commented on docs/source/users/options/fitting_option.rst
> +* ``weigthed_nlls`` - This sets the cost function to be weighted non-linear least squares, :class:`~fitbenchmarking.cost_func.weighted_nlls_cost_func.WeightedNLLSCostFunc`.
```suggestion
* ``weighted_nlls`` - This sets the cost function to be weighted non-linear least squares, :class:`~fitbenchmarking.cost_func.weighted_nlls_cost_func.WeightedNLLSCostFunc`.
```
```suggestion
* ``weigthed_nlls`` - This sets the cost function to be weighted non-linear least squares, :class:`~fitbenchmarking.cost_func.weighted_nlls_cost_func.WeightedNLLSCostFunc`.
```

2020-11-26 16:17 UTC, tyronerees approved these changes

2020-11-26 16:18 UTC, merged