386 add levmar
fitbenchmarking/fitbenchmarking pull request #722
Opened 2021-03-01 14:25 UTC by tyronerees

#### Description of Work

Fixes #386 

#### Testing Instructions

1. Choose levmar in the options
2. Check that the results are consistent
3.

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

2021-03-15 15:11 UTC, AndrewLister-STFC requested changes
Looks good to me, I think there's 1 link that needs updating and I had a couple of suggestions.

It runs on my laptop and gives answers that make sense.

Can you also include it in the regression tests if it's deterministic please.

2021-03-15 15:11 UTC, AndrewLister-STFC commented on fitbenchmarking/controllers/levmar_controller.py
> +                                     jacf=jac)
Formatting suggestion, feel free to ignore.

```suggestion
        self.final_params, _, self._info = levmar.levmar(
            self._feval,
            self.initial_params,
            self.data_y,
            args=(self.data_x,),
            jacf=jac)
```

2021-03-19 15:49 UTC, tyronerees commented on docs/source/users/install_instructions/fitbenchmarking.rst
> +* ``levmar`` -- installs the `levmar <https://github.com/SasView/sasmodels>`_ fitting package.  Note that the interface we use also requires BLAS and LAPLACK to be installed on the system, and calls
```suggestion
* ``levmar`` -- installs the `levmar <http://users.ics.forth.gr/~lourakis/levmar/>`_ fitting package.  Note that the interface we use also requires BLAS and LAPLACK to be installed on the system, and calls to this minimizer will fail if these libraries are not present.
```

2021-03-19 15:51 UTC, tyronerees commented on fitbenchmarking/controllers/levmar_controller.py
> +        fx = self.problem.function(self.data_x, *p)  # (eval_model(params=p)
```suggestion
        fx = self.problem.function(self.data_x, *p) 
```

2021-03-24 15:51 UTC, jess-farmer commented on fitbenchmarking/controllers/levmar_controller.py
> +        return jac
Pylint throws up an unused argument warning for the x argument in these functions

2021-03-24 15:53 UTC, jess-farmer commented
Looks good to me, just thought I would mention the 'unused argument' pylint warning as we're looking to remove all linting errors and warnings

2021-03-24 16:07 UTC, merged