742 flag minimizers not respecting bounds
fitbenchmarking/fitbenchmarking pull request #772
Opened 2021-04-22 13:26 UTC by jess-farmer

#### Description of Work

Fixes #742 

#### Testing Instructions

1. Run fitbenchmarking and check that error flag appears as expected if parameter bounds are not respected (until pull request 771 is merged, using bumps minimizers are a good way to test this)

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

2021-04-23 13:37 UTC, tyronerees requested changes
This looks good.  

Other than the line not hit by the tests, I only have one comment.  The minimizers that don't respect the bounds will usually end up having the smallest residual.  In the table below, I've set '30 < radius < 50' and '325 < length < 375'.  The only minimizer that converges and satisfies these bounds is `levmar:scipy-no-jac`.  Also `dogbox` and `levmar` fail to converge, but both find smaller residuals:
![image](https://user-images.githubusercontent.com/13645545/115878032-fed1f680-a43f-11eb-86f8-0c49f21d2731.png)
I feel the colouring on the table should ignore the results of the minimizers that don't satisfy the bounds -- these should always be darkest red (or potentially another colour to highlight they are different -- darkish blue?).  However, I don't think we should lose the numerical information, as that does tell us something.  

Let me know if this isn't clear and we can chat on zoom

2021-04-23 13:37 UTC, tyronerees commented on fitbenchmarking/core/fitting_benchmarking.py
> +
This line is missed by the tests -- can we add a test to cover it?

2021-04-23 13:52 UTC, tyronerees commented
I should say, I'd also be happy if taking the flagged values out of the table colouring goes in another PR -- this does fix the open issue, and flags it to the user correctly.

2021-04-23 14:06 UTC, jess-farmer commented
Thanks for looking through this @tyronerees, I think it definitely makes sense for the colouring on the table to reflect when a minimizer hasn't respected parameter bounds. I'll look at addressing this (as well the line missed by the tests) within this PR

2021-04-30 09:05 UTC, tyronerees requested changes
Thanks for this.  I think we still need to iterate slightly on this to make sure it's useful to users. Here's the output I get for a problem that Powell fails for, on which I've highlighted the issues:
![image](https://user-images.githubusercontent.com/13645545/116673181-faa35d00-a99a-11eb-808c-823df5be469a.png)

It's obvious now that Powell shouldn't be the best, which is good, but it's not clear how the others compare, as they are all dark red.  I think it might be best to amend the relative number to 'inf' in this case, (but leave the absolute as is), which will not only push the failing minimizer to red, but make the others yellow too.

I hope this is clear (sorry that I wasn't before) -- let me know if you have any questions.

2021-05-05 13:50 UTC, tyronerees approved these changes
This is great -- thanks @jess-farmer!

2021-05-05 13:50 UTC, merged