Add SciPy Global Optimization software
fitbenchmarking/fitbenchmarking pull request #823
Opened 2021-06-02 15:26 UTC by jfowkes

#### Description of Work

Closes #822 

#### Testing Instructions

1. Check that all three SciPy GO minimisers run on a simple test problem with bounds
2. Check that docs have been updated to include scipy_go
3. Check that the new global_optimization algorithm type label works correctly

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

2021-06-03 15:45 UTC, jfowkes commented
@jess-farmer any idea why the default regression tests are not running? I'm getting an error deep in fitbenchmarking: 
```
E       UnboundLocalError: local variable 'unselected_minimzers' referenced before assignment

fitbenchmarking/core/fitting_benchmarking.py:129: UnboundLocalError
```

2021-06-04 11:05 UTC, jess-farmer requested changes
Looks good! I just have a few comments:

- There are a few pylint warnings for the scipy_go_controller:
 ```
 fitbenchmarking/controllers/scipy_go_controller.py:59:8: W0201: Attribute '_maxiter' defined outside __init__ (attribute-defined-outside-init)
fitbenchmarking/controllers/scipy_go_controller.py:79:8: W0201: Attribute 'result' defined outside __init__ (attribute-defined-outside-init)
fitbenchmarking/controllers/scipy_go_controller.py:82:8: W0201: Attribute '_status' defined outside __init__ (attribute-defined-outside-init)
```
- I am finding that `differential_evolution` has an error flag 3 every time I run fitbenchmarking - printing `self.result` shows that although the solver successfully converged there isn't `status` attribute in the results object and this seems to be what's causing the problem.

2021-06-04 13:17 UTC, jfowkes commented on fitbenchmarking/controllers/scipy_go_controller.py
> +            raise MissingBoundsError("SciPy GO requires bounds on parameters")
Agreed will move this into `setup`, also good catch on the `inf` values in `self.value_ranges` will check for that aswell.

2021-06-04 13:18 UTC, jfowkes commented on fitbenchmarking/controllers/tests/test_controllers.py
> +@run_for_test_types(TEST_TYPE, 'default', 'all')
Ah I was confused as to why it wasn't finding mantid, thanks for the fix!

2021-06-04 13:24 UTC, jfowkes commented
> Looks good! I just have a few comments:
> 
> * There are a few pylint warnings for the scipy_go_controller:

Good spot, will fix those!

> * I am finding that `differential_evolution` has an error flag 3 every time I run fitbenchmarking - printing `self.result` shows that although the solver successfully converged there isn't `status` attribute in the results object and this seems to be what's causing the problem.

Yeah this is issue #826 cropping up again, I'll implement per-solver flag handling (it's not going to be pretty as for some solvers I'll have to parse the return messages but it should work consistently at least).

2021-06-07 14:20 UTC, jess-farmer commented
@jfowkes Sorry to add another comment, but just wanted to check if you are able to get results for `shgo`; I've just been checking through your changes and realised that even after leaving fitbenchmarking running for an hour it's still stuck on the `shgo` minimizer - not sure if it's just my computer or something that needs looking into!

2021-06-07 14:43 UTC, jfowkes commented
@jess-farmer good question! The problem is that these SciPy global optimization routines are really not very good and I have them set to 1,000 iterations by default. Perhaps we should reduce the iteration limit for `shgo` to 100 and hope?

2021-06-07 15:53 UTC, jess-farmer commented
@jfowkes yeah that sounds like a good idea to reduce the iteration limit, it would probably also be worth adding a note to the docs (maybe under known issues?) mentioning that `shgo` is particularly slow running and is probably best avoided!

2021-06-08 07:10 UTC, jfowkes commented
@jess-farmer good idea, have done!

2021-06-08 08:20 UTC, jess-farmer commented
Great, thanks, I'll now approve and merge!

2021-06-08 08:21 UTC, merged