270 higher difficulty problems
fitbenchmarking/fitbenchmarking pull request #858
Opened 2021-07-02 10:41 UTC by jess-farmer

#### Description of Work

Fixes #270 

#### Testing Instructions

1. Run the new problem set with various options
2.
3.

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

2021-07-02 10:55 UTC, jess-farmer commented
@tyronerees I have added 4 problems from those found [here](https://github.com/scipy/scipy/tree/master/benchmarks/benchmarks/go_benchmark_functions) which work with fitbenchmarking. I have also included `KOWOSBNE.SIF` and `MEYER3NE.SIF` (which were on the list that Nick provided) although these SIF files currently cause errors when fitbenchmarking tries to parse the problem. Looking at these problems, they seem to be the same as `MGH09.dat` and `MGH10.dat` in the `NIST/high_difficulty` problem set - I've also noticed that these problems exist in `cutest/mastif` as `MGH09.SIF` and `MGH10.SIF`, so I wonder if I could use these instead of the two SIF files currently causing issues?

2021-07-02 13:36 UTC, tyronerees commented
@jess-farmer good spot!  Yes, I think that makes sense -- copy those files over in place of KOWOSBNE and MEYER3NE and add the bounds in the GO directory.  I still don't see where the 'x' data comes from in KOWOSBNE/MEYER3NE, but I'm sure it's generated somehow since they are nice and straightforward.

2021-07-05 08:36 UTC, tyronerees requested changes
These all run and look good and sensible -- many thanks, @jess-farmer!

Could you add a short description of these problems here: https://fitbenchmarking--858.org.readthedocs.build/en/858/users/BenchmarkProblems.html Don't worry about the zip/tar.gz files -- I think it makes sense to add these when we do a new release.  

I'll add an issue to document what we need to do when adding new data sets, because this is not at all clear.

2021-07-06 08:42 UTC, tyronerees approved these changes

2021-07-06 08:43 UTC, merged