Create User Install Test in github actions
fitbenchmarking/fitbenchmarking pull request #923
Opened 2021-09-20 12:52 UTC by robertapplin

#### Description of Work

Fixes #753

#### Testing Instructions

1.
2.
3.

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

2021-09-21 10:39 UTC, robertapplin commented
Confirmed that the nightly build for a release install on windows (`@github-actions
Nightly Build / Release Install Test (Windows)`) will fail for Python 3.9, but not for Python 3.8.

2021-09-21 10:47 UTC, robertapplin commented
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |

2021-09-21 15:37 UTC, tyronerees commented
I think:
- both Windows and Linux
- from pip (I think the release is already covered in other tests, although we can add this later if needed)
- I'd start with 3.9, and we could always add more down the line.

2021-09-22 08:32 UTC, robertapplin commented
> I think:
> 
> * both Windows and Linux
> * from pip (I think master is already covered in other tests, although we can add this later if needed)
> * I'd start with 3.9, and we could always add more down the line.

Sounds good. If we merge this before #924 then we should see that the windows py3.9 nightly will fail at midnight (hopefully)

2021-10-05 09:14 UTC, tyronerees requested changes
`gradient_free` and `numdifftools` are options in the master branch, but aren't supported in the lastest release (version 0.1.4 -- https://fitbenchmarking.readthedocs.io/en/v0.1.4/users/install_instructions/fitbenchmarking.html)
This looks good once we remove these -- thanks!

2021-10-05 09:14 UTC, tyronerees commented on .github/workflows/nightly.yml
> +        python -m pip install fitbenchmarking[bumps,DFO,gradient_free,minuit,SAS,numdifftools]
```suggestion
        python -m pip install fitbenchmarking[bumps,DFO,minuit,SAS]
```

2021-10-05 09:14 UTC, tyronerees commented on .github/workflows/nightly.yml
> +        python -m pip install fitbenchmarking[bumps,DFO,gradient_free,minuit,SAS,numdifftools]
```suggestion
        python -m pip install fitbenchmarking[bumps,DFO,minuit,SAS]
```

2021-10-05 09:28 UTC, tyronerees submitted a review, later dismissed

2021-10-05 09:36 UTC, tyronerees approved these changes

2021-10-05 09:36 UTC, merged