Add `dfo`, `gradient_free` and `minuit` to the regression tests
fitbenchmarking/fitbenchmarking pull request #968
Opened 2021-11-03 13:59 UTC by robertapplin

#### Description of Work
This PR adds the `dfo`, `gradient_free` and `minuit` software packages to the regression tests.

Fixes #939

#### Testing Instructions

1. Make sure the regression tests pass and the results look sensible.

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

2021-11-09 13:47 UTC, robertapplin commented
I have tracked down the source of the unreliable results to a block of code in iminuit which is parallelized. I did this by first looking at the differing outputs at the start of the fit (using `print_level = 3`):

**A**
![image](https://user-images.githubusercontent.com/40830825/140935021-478e0c3d-a6f8-43ef-911e-9999a4b9884e.png)

**B**
![image](https://user-images.githubusercontent.com/40830825/140935323-81333ac8-174e-4a5c-adb8-4ff1b1f0dc3d.png)

If you follow the print statements in the output, you will find yourself in the `MnSeedGenerator`

and on line ... it calculates the initial gradient (which matches for both) before calculuting

2021-11-09 14:16 UTC, robertapplin commented
These slides talk about some of the parallelization work done in Minuit2 https://indico.cern.ch/event/36763/contributions/871192/attachments/730869/1002804/ParallelMinuit_27Jun.pdf

2021-11-11 11:18 UTC, robertapplin commented
It seems that slight rounding differences across machines might be causing the small numerical differences in the calculations. I am going to try to reduce the precision of the calculation to see if the calculations become more reliable. The machine currently uses double precision (16 decimal places), so I will try limit precision to 14 or 15 decimal places.

2021-11-11 16:26 UTC, robertapplin commented
Changing the precision didn't prevent all numerical instabilities. I think the solution is to only test minuit with problem sets that give a numerically stable solution. I have started to do a bit of a refactor in `test_regression` to make it easier to do this.

@AndrewLister-STFC I have copied the numerically stable datasets into a separate directory called `minuit_set` so I can use them for testing minuit. But having the same data in two different locations seems bad - any ideas how we could do this better?

2021-11-18 16:22 UTC, AndrewLister-STFC requested changes
All looks good to me bar some very minor suggestions, I'm surprised that the cubic needed to be swapped out, but I don't think it matters.

2021-11-18 16:22 UTC, AndrewLister-STFC commented on fitbenchmarking/systests/test_regression.py
> +    :rtype: list of list of strings and str
I think this may be clearer as a more concise description
```suggestion
    :rtype: list[list[str]], str
```

2021-11-18 16:22 UTC, AndrewLister-STFC commented on fitbenchmarking/systests/test_regression.py
> +                                 '{}_expected_results'.format(platform),
```suggestion
                                 f'{platform}_expected_results',
```

2021-11-19 13:35 UTC, AndrewLister-STFC approved these changes

2021-11-19 13:44 UTC, merged